export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  LOGIN_LOGOUT_REQUEST: "LOGIN_LOGOUT_REQUEST",
  LOGIN_LOGOUT_SUCCESS: "LOGIN_LOGOUT_SUCCESS",


  //Presnt team
  PRESENT_TEAM_REQUEST: "PRESENT_TEAM_REQUEST",
  PRESENT_TEAM_SUCCESS: "PRESENT_TEAM_SUCCESS",
  PRESENT_TEAM_FAILURE: "PRESENT_TEAM_FAILURE",
  //Leaves
  GET_LEAVES_REQUEST: "GET_LEAVES_REQUEST",
  GET_LEAVES_SUCCESS: "GET_LEAVES_SUCCESS",
  GET_LEAVES_FAILURE: "GET_LEAVES_FAILURE",
  //GET request
  GET_REQUEST: "GET_REQUEST",
  GET_SUCCESS: "GET_SUCCESS",
  GET_FAILURE: "GET_FAILURE",
  //GetAttendenceCountsAll
  GET_ATDNCE_COUNTSALL_REQUEST: "GET_ATDNCE_COUNTSALL_REQUEST",
  GET_ATDNCE_COUNTSALL_SUCCESS: "GET_ATDNCE_COUNTSALL_SUCCESS",
  GET_ATDNCE_COUNTSALL_FAILURE: "GET_ATDNCE_COUNTSALL_FAILURE",
  //get user  profile'
  GET_USER_PROFILE_REQUEST: 'GET_USER_PROFILE_REQUEST',
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",
  //get mothly attendance record of user
  GET_MOTHLY_ATTENDANCE_OF_USER_REQUEST: "GET_MOTHLY_ATTENDANCE_OF_USER_REQUEST",
  GET_MOTHLY_ATTENDANCE_OF_USER_SUCCESS: "GET_MOTHLY_ATTENDANCE_OF_USER_SUCCESS",
  GET_MOTHLY_ATTENDANCE_OF_USER_FAILURE: "GET_MOTHLY_ATTENDANCE_OF_USER_FAILURE",
  //get late user'
  GET_LATE_USER_REQUEST: 'GET_LATE_USER_REQUEST',
  GET_LATE_USER_SUCCESS: "GET_LATE_USER_SUCCESS",
  GET_LATE_USER_FAILURE: "GET_LATE_USER_FAILURE",
};
