export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  //LOGIN
  PRESENT_TEAM_REQUEST: "PRESENT_TEAM_REQUEST",
  PRESENT_TEAM_SUCCESS: "PRESENT_TEAM_SUCCESS",
  PRESENT_TEAM_FAILURE: "PRESENT_TEAM_FAILURE",



};
