export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  //Presnt team
  PRESENT_TEAM_REQUEST: "PRESENT_TEAM_REQUEST",
  PRESENT_TEAM_SUCCESS: "PRESENT_TEAM_SUCCESS",
  PRESENT_TEAM_FAILURE: "PRESENT_TEAM_FAILURE",
<<<<<<< Updated upstream
//Leaves
GET_LEAVES_REQUEST:"GET_LEAVES_REQUEST",
GET_LEAVES_SUCCESS:"GET_LEAVES_SUCCESS",
GET_LEAVES_FAILURE:"GET_LEAVES_FAILURE",
//GET request
GET_REQUEST:"GET_REQUEST",
GET_SUCCESS:"GET_SUCCESS",
GET_FAILURE:"GET_FAILURE",
=======
  //GetAttendenceCountsAll
  GET_ATDNCE_COUNTSALL_REQUEST: "GET_ATDNCE_COUNTSALL_REQUEST",
  GET_ATDNCE_COUNTSALL_SUCCESS: "GET_ATDNCE_COUNTSALL_SUCCESS",
  GET_ATDNCE_COUNTSALL_FAILURE: "GET_ATDNCE_COUNTSALL_FAILURE",


>>>>>>> Stashed changes
};
