export const routeName = {
  LANDING_SCREEN:"LANDING_SCREEN",
  NOTIFICATION:"NOTIFICATION",
  ATTENDENCE_DETAIL:"ATTENDENCE_DETAIL",
  SPLASH: 'SPLASH',
  LOGIN:'LOGIN',
  FORGOT_PASSWORD:'FORGOT_PASSWORD',
  CHANGE_PASSWORD:'CHANGE_PASSWORD',
  VERIFICATION_CODE:'VERIFICATION_CODE',


  BOTTOM_TABS:'BOTTOM_TABS',
  PRESENT_TEAM:'PRESENT_TEAM',
  DASHBOARD:'DASHBOARD',
  APPLY_LATE:"APPLY_LATE",
  LEAVES:"LEAVES",
  REQUEST:"REQUEST",
  ADDREQUEST:"ADDREQUEST",
  PROFILE:"PROFILE",
  LATECOMER:"LATECOMER",
  APPLYLEAVES:"APPLYLEAVES",
  USERS:'USERS',
  EMPLOYEE_PROFILE:'EMPLOYEE_PROFILE',
  ALL_EMP_DATA:'ALL_EMP_DATA',
  SEND_NOTIFICATIONS:'SendNotifications'
};
