export const routeName = {
  LANDING_SCREEN:"LANDING_SCREEN",
  NOTIFICATION:"NOTIFICATION",
  ATTENDENCE_DETAIL:"ATTENDENCE_DETAIL",
  SPLASH: 'SPLASH',
  LOGIN:'LOGIN',
  BOTTOM_TABS:'BOTTOM_TABS',
  PRESENT_TEAM:'PRESENT_TEAM',
  DASHBOARD:'DASHBOARD',
  LEAVES:"LEAVES",
  REQUEST:"REQUEST",
  PROFILE:"PROFILE",

};
